---
- name: Install mysql-server and python-mysqldb
  apt: pkg={{ item }}
  with_items:
    - mysql-server
    - python-mysqldb
  tags: mysql

- name: Update mysql root password for all root accounts
  mysql_user: name="root" host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Copy .my.cnf file with root password credentials
  template: src=root-my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  tags: mysql

- name: Delete anonymous MySQL server user
  mysql_user: user="" host={{ item }} state="absent"
  with_items:
    - $server_hostname
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Remove the MySQL test database
  mysql_db: db=test state=absent
  tags: mysql

- name: Copy ops_test database dump file
  copy: src=dump.sql.bz2 dest=/tmp owner=root group=root mode=0644
  tags: mysql

- name: Create database ops_test
  mysql_db: name=ops_test state=present encoding=utf8
  tags: mysql

- name: Import ops_test database dump file
  mysql_db: name=ops_test state=import target=/tmp/dump.sql.bz2
  tags: mysql

- name: Remove ops_test database dump file
  file: name=/tmp/dump.sql.bz2 state=absent
  tags: mysql

- name: Copy backup_mysql_db to /etc/cron.daily
  template: src=backup_mysql_db.j2 dest=/etc/cron.daily/backup_mysql_db owner=root group=root mode=0755
  tags: mysql
