---
- name: Update and upgrade system
  apt: upgrade=yes update-cache=yes
  tags: common

- name: Update language
  apt: pkg=language-pack-en
  tags: common

- name: Update locale to {{ locale }}
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  tags: common

- name: Update localtime to {{ timezone }}
  command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime
  tags: common

- name: Set timezone to {{ timezone }}
  template: src=default-timezone.j2 dest=/etc/timezone
  tags: common

- name: Update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  tags: common

- name: Stopping puppet agent/chef client
  service: name={{ item }} state=stopped enabled=no
  with_items:
    - puppet
    - chef-client
  tags: common
