---
- name: Update apt cache and upgrade system
  apt: upgrade=dist update-cache=yes
  sudo: yes
  tags: 
    - common
    - update
    - upgrade

- name: Update language
  apt: pkg=language-pack-en
  sudo: yes
  tags:
    - common
    - language

- name: Set LANG to en_US.UTF-8
  lineinfile: dest=/etc/default/locale line='LANG="en_US.UTF-8"'
  sudo: yes
  tags: 
    - common
    - language

- name: Set LC_ALL to en_US.UTF-8
  lineinfile: dest=/etc/default/locale line='LC_ALL="en_US.UTF-8"'
  sudo: yes
  tags: 
    - common
    - language

- name: Stopping and disabling puppet agent
  service: name=puppet state=stopped enabled=no
  sudo: yes
  tags:
    - common
    - puppet
    - config

- name: Stopping and disabling chef client
  service: name=chef-client state=stopped enabled=no
  sudo: yes
  tags:
    - common
    - chef-client
    - config

#- name: Install gcc
#  apt: pkg=gcc
#  tags: common

#- name: Install g++
#  apt: pkg=g++
#  tags: common

#- name: Install make
#  apt: pkg=make
#  tags: common
